export class TitleDetailHTML {
    public static readonly notFollowing: string = `<div class="row m-0 py-1 px-0 border-top">
    <div class="col-lg-3 col-xl-2 strong">Actions:</div>
    <div class="col-lg-9 col-xl-10">
        <button class="btn btn-secondary" id="upload_button"><span class="fas fa-upload fa-fw " aria-hidden="true" title="Upload"></span> <span class="d-none d-xl-inline">Upload chapter</span></button>						<div class="btn-group "><button id="1" data-manga-id="23279" type="button" class="btn btn-secondary manga_follow_button"><span class="fas fa-bookmark fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Follow</span></button>
<button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
</button><div class="dropdown-menu dropdown-menu-right"><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="1" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Reading</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="2" href="#"><span class="fas fa-check fa-fw " aria-hidden="true" title="Follow"></span> Completed</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="3" href="#"><span class="fas fa-pause fa-fw " aria-hidden="true" title="Follow"></span> On hold</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="4" href="#"><span class="fas fa-calendar-alt fa-fw " aria-hidden="true" title="Follow"></span> Plan to read</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="5" href="#"><span class="fas fa-trash fa-fw " aria-hidden="true" title="Follow"></span> Dropped</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="6" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Re-reading</a></div>
<input type="button" value="Hide" id="hide-button"></div>						<div class="btn-group ">
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-star fa-fw " aria-hidden="true"></span>  <span class="caret"></span>
</button>
<div class="dropdown-menu"><a class=" dropdown-item manga_rating_button" id="10" data-manga-id="23279" href="#">(10) Masterpiece</a><a class=" dropdown-item manga_rating_button" id="9" data-manga-id="23279" href="#">(9) Great</a><a class=" dropdown-item manga_rating_button" id="8" data-manga-id="23279" href="#">(8) Very good</a><a class=" dropdown-item manga_rating_button" id="7" data-manga-id="23279" href="#">(7) Good</a><a class=" dropdown-item manga_rating_button" id="6" data-manga-id="23279" href="#">(6) Fine</a><a class=" dropdown-item manga_rating_button" id="5" data-manga-id="23279" href="#">(5) Average</a><a class=" dropdown-item manga_rating_button" id="4" data-manga-id="23279" href="#">(4) Bad</a><a class=" dropdown-item manga_rating_button" id="3" data-manga-id="23279" href="#">(3) Very bad</a><a class=" dropdown-item manga_rating_button" id="2" data-manga-id="23279" href="#">(2) Horrible</a><a class=" dropdown-item manga_rating_button" id="1" data-manga-id="23279" href="#">(1) Appalling</a></div>
</div>																			<button type="button" class="btn btn-warning float-right mr-1" data-toggle="modal" data-target="#manga_report_modal"><span class="fas fa-flag fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Report</span></button>
                            </div>
</div>`
    public static readonly reading: string = `<div class="row m-0 py-1 px-0 border-top">
    <div class="col-lg-3 col-xl-2 strong">Actions:</div>
    <div class="col-lg-9 col-xl-10">
        <button class="btn btn-secondary" id="upload_button"><span class="fas fa-upload fa-fw " aria-hidden="true" title="Upload"></span> <span class="d-none d-xl-inline">Upload chapter</span></button>						<div class="btn-group "><button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-eye fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Reading</span></button><div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item manga_unfollow_button" id="23279" data-manga-id="23279" href="#"><span class="fas fa-bookmark fa-fw " aria-hidden="true" title="Unfollow"></span> Unfollow</a><a class="disabled dropdown-item manga_follow_button" data-manga-id="23279" id="1" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Reading</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="2" href="#"><span class="fas fa-check fa-fw " aria-hidden="true" title="Follow"></span> Completed</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="3" href="#"><span class="fas fa-pause fa-fw " aria-hidden="true" title="Follow"></span> On hold</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="4" href="#"><span class="fas fa-calendar-alt fa-fw " aria-hidden="true" title="Follow"></span> Plan to read</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="5" href="#"><span class="fas fa-trash fa-fw " aria-hidden="true" title="Follow"></span> Dropped</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="6" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Re-reading</a></div>
<input type="button" value="Hide" id="hide-button"></div>						<div class="btn-group ">
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-star fa-fw " aria-hidden="true"></span>  <span class="caret"></span>
</button>
<div class="dropdown-menu"><a class=" dropdown-item manga_rating_button" id="10" data-manga-id="23279" href="#">(10) Masterpiece</a><a class=" dropdown-item manga_rating_button" id="9" data-manga-id="23279" href="#">(9) Great</a><a class=" dropdown-item manga_rating_button" id="8" data-manga-id="23279" href="#">(8) Very good</a><a class=" dropdown-item manga_rating_button" id="7" data-manga-id="23279" href="#">(7) Good</a><a class=" dropdown-item manga_rating_button" id="6" data-manga-id="23279" href="#">(6) Fine</a><a class=" dropdown-item manga_rating_button" id="5" data-manga-id="23279" href="#">(5) Average</a><a class=" dropdown-item manga_rating_button" id="4" data-manga-id="23279" href="#">(4) Bad</a><a class=" dropdown-item manga_rating_button" id="3" data-manga-id="23279" href="#">(3) Very bad</a><a class=" dropdown-item manga_rating_button" id="2" data-manga-id="23279" href="#">(2) Horrible</a><a class=" dropdown-item manga_rating_button" id="1" data-manga-id="23279" href="#">(1) Appalling</a></div>
</div>																			<button type="button" class="btn btn-warning float-right mr-1" data-toggle="modal" data-target="#manga_report_modal"><span class="fas fa-flag fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Report</span></button>
                            </div>
</div>`;
    public static readonly planToRead: string = `<div class="row m-0 py-1 px-0 border-top">
    <div class="col-lg-3 col-xl-2 strong">Actions:</div>
    <div class="col-lg-9 col-xl-10">
        <button class="btn btn-secondary" id="upload_button"><span class="fas fa-upload fa-fw " aria-hidden="true" title="Upload"></span> <span class="d-none d-xl-inline">Upload chapter</span></button>						<div class="btn-group "><button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-calendar-alt fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Plan to read</span></button><div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item manga_unfollow_button" id="23279" data-manga-id="23279" href="#"><span class="fas fa-bookmark fa-fw " aria-hidden="true" title="Unfollow"></span> Unfollow</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="1" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Reading</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="2" href="#"><span class="fas fa-check fa-fw " aria-hidden="true" title="Follow"></span> Completed</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="3" href="#"><span class="fas fa-pause fa-fw " aria-hidden="true" title="Follow"></span> On hold</a><a class="disabled dropdown-item manga_follow_button" data-manga-id="23279" id="4" href="#"><span class="fas fa-calendar-alt fa-fw " aria-hidden="true" title="Follow"></span> Plan to read</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="5" href="#"><span class="fas fa-trash fa-fw " aria-hidden="true" title="Follow"></span> Dropped</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="6" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Re-reading</a></div>
<input type="button" value="Hide" id="hide-button"></div>						<div class="btn-group ">
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-star fa-fw " aria-hidden="true"></span>  <span class="caret"></span>
</button>
<div class="dropdown-menu"><a class=" dropdown-item manga_rating_button" id="10" data-manga-id="23279" href="#">(10) Masterpiece</a><a class=" dropdown-item manga_rating_button" id="9" data-manga-id="23279" href="#">(9) Great</a><a class=" dropdown-item manga_rating_button" id="8" data-manga-id="23279" href="#">(8) Very good</a><a class=" dropdown-item manga_rating_button" id="7" data-manga-id="23279" href="#">(7) Good</a><a class=" dropdown-item manga_rating_button" id="6" data-manga-id="23279" href="#">(6) Fine</a><a class=" dropdown-item manga_rating_button" id="5" data-manga-id="23279" href="#">(5) Average</a><a class=" dropdown-item manga_rating_button" id="4" data-manga-id="23279" href="#">(4) Bad</a><a class=" dropdown-item manga_rating_button" id="3" data-manga-id="23279" href="#">(3) Very bad</a><a class=" dropdown-item manga_rating_button" id="2" data-manga-id="23279" href="#">(2) Horrible</a><a class=" dropdown-item manga_rating_button" id="1" data-manga-id="23279" href="#">(1) Appalling</a></div>
</div>																			<button type="button" class="btn btn-warning float-right mr-1" data-toggle="modal" data-target="#manga_report_modal"><span class="fas fa-flag fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Report</span></button>
                            </div>
</div>`; 
    public static readonly dropped: string = `<div class="row m-0 py-1 px-0 border-top">
    <div class="col-lg-3 col-xl-2 strong">Actions:</div>
    <div class="col-lg-9 col-xl-10">
        <button class="btn btn-secondary" id="upload_button"><span class="fas fa-upload fa-fw " aria-hidden="true" title="Upload"></span> <span class="d-none d-xl-inline">Upload chapter</span></button>						<div class="btn-group "><button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-trash fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Dropped</span></button><div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item manga_unfollow_button" id="23279" data-manga-id="23279" href="#"><span class="fas fa-bookmark fa-fw " aria-hidden="true" title="Unfollow"></span> Unfollow</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="1" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Reading</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="2" href="#"><span class="fas fa-check fa-fw " aria-hidden="true" title="Follow"></span> Completed</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="3" href="#"><span class="fas fa-pause fa-fw " aria-hidden="true" title="Follow"></span> On hold</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="4" href="#"><span class="fas fa-calendar-alt fa-fw " aria-hidden="true" title="Follow"></span> Plan to read</a><a class="disabled dropdown-item manga_follow_button" data-manga-id="23279" id="5" href="#"><span class="fas fa-trash fa-fw " aria-hidden="true" title="Follow"></span> Dropped</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="6" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Re-reading</a></div>
<input type="button" value="Hide" id="hide-button"></div>						<div class="btn-group ">
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-star fa-fw " aria-hidden="true"></span>  <span class="caret"></span>
</button>
<div class="dropdown-menu"><a class=" dropdown-item manga_rating_button" id="10" data-manga-id="23279" href="#">(10) Masterpiece</a><a class=" dropdown-item manga_rating_button" id="9" data-manga-id="23279" href="#">(9) Great</a><a class=" dropdown-item manga_rating_button" id="8" data-manga-id="23279" href="#">(8) Very good</a><a class=" dropdown-item manga_rating_button" id="7" data-manga-id="23279" href="#">(7) Good</a><a class=" dropdown-item manga_rating_button" id="6" data-manga-id="23279" href="#">(6) Fine</a><a class=" dropdown-item manga_rating_button" id="5" data-manga-id="23279" href="#">(5) Average</a><a class=" dropdown-item manga_rating_button" id="4" data-manga-id="23279" href="#">(4) Bad</a><a class=" dropdown-item manga_rating_button" id="3" data-manga-id="23279" href="#">(3) Very bad</a><a class=" dropdown-item manga_rating_button" id="2" data-manga-id="23279" href="#">(2) Horrible</a><a class=" dropdown-item manga_rating_button" id="1" data-manga-id="23279" href="#">(1) Appalling</a></div>
</div>																			<button type="button" class="btn btn-warning float-right mr-1" data-toggle="modal" data-target="#manga_report_modal"><span class="fas fa-flag fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Report</span></button>
                            </div>
</div>`;
    public static readonly completed: string = `<div class="row m-0 py-1 px-0 border-top">
    <div class="col-lg-3 col-xl-2 strong">Actions:</div>
    <div class="col-lg-9 col-xl-10">
        <button class="btn btn-secondary" id="upload_button"><span class="fas fa-upload fa-fw " aria-hidden="true" title="Upload"></span> <span class="d-none d-xl-inline">Upload chapter</span></button>						<div class="btn-group "><button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-check fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Completed</span></button><div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item manga_unfollow_button" id="23279" data-manga-id="23279" href="#"><span class="fas fa-bookmark fa-fw " aria-hidden="true" title="Unfollow"></span> Unfollow</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="1" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Reading</a><a class="disabled dropdown-item manga_follow_button" data-manga-id="23279" id="2" href="#"><span class="fas fa-check fa-fw " aria-hidden="true" title="Follow"></span> Completed</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="3" href="#"><span class="fas fa-pause fa-fw " aria-hidden="true" title="Follow"></span> On hold</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="4" href="#"><span class="fas fa-calendar-alt fa-fw " aria-hidden="true" title="Follow"></span> Plan to read</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="5" href="#"><span class="fas fa-trash fa-fw " aria-hidden="true" title="Follow"></span> Dropped</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="6" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Re-reading</a></div>
<input type="button" value="Hide" id="hide-button"></div>						<div class="btn-group ">
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-star fa-fw " aria-hidden="true"></span>  <span class="caret"></span>
</button>
<div class="dropdown-menu"><a class=" dropdown-item manga_rating_button" id="10" data-manga-id="23279" href="#">(10) Masterpiece</a><a class=" dropdown-item manga_rating_button" id="9" data-manga-id="23279" href="#">(9) Great</a><a class=" dropdown-item manga_rating_button" id="8" data-manga-id="23279" href="#">(8) Very good</a><a class=" dropdown-item manga_rating_button" id="7" data-manga-id="23279" href="#">(7) Good</a><a class=" dropdown-item manga_rating_button" id="6" data-manga-id="23279" href="#">(6) Fine</a><a class=" dropdown-item manga_rating_button" id="5" data-manga-id="23279" href="#">(5) Average</a><a class=" dropdown-item manga_rating_button" id="4" data-manga-id="23279" href="#">(4) Bad</a><a class=" dropdown-item manga_rating_button" id="3" data-manga-id="23279" href="#">(3) Very bad</a><a class=" dropdown-item manga_rating_button" id="2" data-manga-id="23279" href="#">(2) Horrible</a><a class=" dropdown-item manga_rating_button" id="1" data-manga-id="23279" href="#">(1) Appalling</a></div>
</div>																			<button type="button" class="btn btn-warning float-right mr-1" data-toggle="modal" data-target="#manga_report_modal"><span class="fas fa-flag fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Report</span></button>
                            </div>
</div>`;
    public static readonly onHold: string = `<div class="row m-0 py-1 px-0 border-top">
    <div class="col-lg-3 col-xl-2 strong">Actions:</div>
    <div class="col-lg-9 col-xl-10">
        <button class="btn btn-secondary" id="upload_button"><span class="fas fa-upload fa-fw " aria-hidden="true" title="Upload"></span> <span class="d-none d-xl-inline">Upload chapter</span></button>						<div class="btn-group "><button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-pause fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">On hold</span></button><div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item manga_unfollow_button" id="23279" data-manga-id="23279" href="#"><span class="fas fa-bookmark fa-fw " aria-hidden="true" title="Unfollow"></span> Unfollow</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="1" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Reading</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="2" href="#"><span class="fas fa-check fa-fw " aria-hidden="true" title="Follow"></span> Completed</a><a class="disabled dropdown-item manga_follow_button" data-manga-id="23279" id="3" href="#"><span class="fas fa-pause fa-fw " aria-hidden="true" title="Follow"></span> On hold</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="4" href="#"><span class="fas fa-calendar-alt fa-fw " aria-hidden="true" title="Follow"></span> Plan to read</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="5" href="#"><span class="fas fa-trash fa-fw " aria-hidden="true" title="Follow"></span> Dropped</a><a class=" dropdown-item manga_follow_button" data-manga-id="23279" id="6" href="#"><span class="fas fa-eye fa-fw " aria-hidden="true" title="Follow"></span> Re-reading</a></div>
<input type="button" value="Hide" id="hide-button"></div>						<div class="btn-group ">
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-star fa-fw " aria-hidden="true"></span>  <span class="caret"></span>
</button>
<div class="dropdown-menu"><a class=" dropdown-item manga_rating_button" id="10" data-manga-id="23279" href="#">(10) Masterpiece</a><a class=" dropdown-item manga_rating_button" id="9" data-manga-id="23279" href="#">(9) Great</a><a class=" dropdown-item manga_rating_button" id="8" data-manga-id="23279" href="#">(8) Very good</a><a class=" dropdown-item manga_rating_button" id="7" data-manga-id="23279" href="#">(7) Good</a><a class=" dropdown-item manga_rating_button" id="6" data-manga-id="23279" href="#">(6) Fine</a><a class=" dropdown-item manga_rating_button" id="5" data-manga-id="23279" href="#">(5) Average</a><a class=" dropdown-item manga_rating_button" id="4" data-manga-id="23279" href="#">(4) Bad</a><a class=" dropdown-item manga_rating_button" id="3" data-manga-id="23279" href="#">(3) Very bad</a><a class=" dropdown-item manga_rating_button" id="2" data-manga-id="23279" href="#">(2) Horrible</a><a class=" dropdown-item manga_rating_button" id="1" data-manga-id="23279" href="#">(1) Appalling</a></div>
</div>																			<button type="button" class="btn btn-warning float-right mr-1" data-toggle="modal" data-target="#manga_report_modal"><span class="fas fa-flag fa-fw " aria-hidden="true"></span> <span class="d-none d-xl-inline">Report</span></button>
                            </div>
</div>`;
}